default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: carv
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: hogarinmo_development

test:
  <<: *default
  database: hogarinmo_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: 15
